project:
  type: website

website:
  title: "Methods & Workshops"
  navbar:
    right:
      - href: index.qmd
        text: Start
      - href: workshops/index.qmd
        text: Workshops

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
