project:
  type: website

website:
  title: "Methods"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Test"
        href: test.qmd
      - text: "Ãœber mich"
        href: about.qmd
  sidebar:
    - id: test
      title: "Inhalte"
      style: docked
      contents:
        - text: "Abschnitt A"
          href: "#a"
        - text: "Abschnitt B"
          href: "#b"

format:
  html:
    theme: default
