project:
  type: website

website:
  title: "Methods"
  navbar:
    right:
      - text: "Startseite"
        href: index.qmd
      - text: "Über mich"
        href: ueber-mich.qmd
      - text: "Materialien"
        href: materialien.qmd
      - text: "Workshops"
        menu:
          - text: "Workshops Überblick"
            href: workshops/overview.qmd
          - text: "Einführung"
            href: workshops/workshop1/index.qmd
          - text: "Workshop 2"
            href: workshops/workshop1/index.qmd
          - text: "Workshop 3"
            href: workshops/workshop1/index.qmd
          - text: "Workshop 4"
            href: workshops/workshop1/index.qmd
            
            

format:
  html:
    theme: darkly
    css:
      - style.css
      - assets/css/workshop.css
    toc: false
