project:
  type: website

website:
  title: "Methods"

  navbar:
    right:
      - text: "Startseite"
        href: index.qmd
      - text: "Ãœber mich"
        href: ueber-mich.qmd
      - text: "Materialien"
        href: materialien.qmd
      - text: "Workshops"
        menu:
          - text: "Workshops Ãœberblick"
            href: workshops/overview.qmd
          - text: "Workshop 1 â€“ EinfÃ¼hrung in R"
            href: workshops/workshop1/index.qmd

  # ðŸ”‘ WICHTIG: Sidebar global erlauben
  sidebar:
    collapse-level: 1

format:
  html:
    theme: darkly
    css:
      - style.css
      - assets/css/workshop.css
    toc: false
