project:
  type: website

website:
  title: "Methods"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Test"
        href: test.qmd
      - text: "Über mich"
        href: about.qmd
      - text: "Materialien"
        href: materials.qmd
      - text: "Workshops"
        menu: 
          - text: "Einführung in RStudio"
            href: workshops/ws1/index.qmd
          - text: "Datenvisualisierung mit ggplot2"
            href: workshops/ws2/index.qmd
          - text: "Reproduzierbare Berichte mit Quarto"
            href: workshops/ws3/index.qmd
          - text: "Datenanalyse mit dplyr"
            href: workshops/ws4/index.qmd  
  sidebar:
    id: workshop1
    title: ""
    style: docked
    contents:
      - text: "zum Workshop-Inhalt"
        href: workshops/ws1/day1.qmd

format:
  html:
    theme: default
    css: styles.css
