project:
  type: website
  resources:
    - shinylive-app/**

website:
  title: "Methods"
  navbar:
    right:
      - text: "Startseite"
        href: index.qmd
      - text: "Über mich"
        href: ueber-mich.qmd
      - text: "Materialien"
        href: materialien.qmd
      - text: "Workshops"
        menu:
          - text: "Workshops Überblick"
            href: workshops/overview.qmd
          - text: "Workshop 1 – Einführung in R"
            href: workshops/workshop1/index.qmd
          - text: "Workshop 2 – Datenvisualisierung"
            href: workshops/workshop2/index.qmd
          - text: "Workshop 3 – Qualitative Methoden"
            href: workshops/workshop3/index.qmd
          - text: "Workshop 4 – Statistik & Modelle"
            href: workshops/workshop4/index.qmd

format:
  html:
    theme: darkly
    css:
      - style.css
      - _layouts/assets/css/workshop.css
    toc: true
    toc-depth: 2
