project:
  type: website

website:
  title: "Methods"

  navbar:
    right:
      - text: "Startseite"
        href: index.qmd
      - text: "Über mich"
        href: ueber-mich.qmd
      - text: "Materialien"
        href: materialien.qmd
      - text: "Workshops"
        menu:
          - text: "Workshops Überblick"
            href: workshops/overview.qmd
          - text: "Workshop 1 – Einführung in R"
            href: workshops/workshop1/index.qmd
          - text: "Testseite"
            href: test.qmd

  # Sidebar-Konfiguration für Workshop-Seiten
  sidebar:
    - id: workshops
      title: "Workshops"
      style: floating
      contents:
        - text: "Workshops Überblick"
          href: workshops/overview.qmd
        - text: "Workshop 1 – Einführung in R"
          href: workshops/workshop1/index.qmd
        - text: "Testseite (Workshop XYZ)"
          href: test.qmd

format:
  html:
    theme: darkly
    css:
      - style.css
    toc: true
    toc-depth: 2
